// Generated by nitro
declare module '@nuxt/nitro' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/index': Awaited<ReturnType<typeof import('../server/api/index').default>>
    '/api/article': Awaited<ReturnType<typeof import('../server/api/article').default>>
  }
}
export {}