// Generated by nuxi
/// <reference types="nuxt-windicss" />
/// <reference path="nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path="plugins.d.ts" />
/// <reference path="vue-shim.d.ts" />
/// <reference types="vue-router" />
/// <reference path="middleware.d.ts" />
/// <reference path="auto-imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
